languageCode = "de-de"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://xhain.s3-website.eu-central-1.amazonaws.com"
canonifyurls = true

theme = "hugo-uno"

DefaultContentLanguage = "de"

[Languages]
[Languages.de]
weight = 1
title = "xhain"
description = "Hack- & Makespace im Herzen von Friedrichshain, Bastelstube für Technikinteressierte + Raum für Netzpolitisches"

[Languages.en]
weight = 2
title = "xhain"
description = " "

[indexes]
   category = "categories"
   tag = "tags"

[Params]
  github = "xHain-hackspace"
  twitter = "xHain_hackspace"
  email = "x-hain@posteo.de"
  slack = "xhain"

  cover = "/images/background-cover.jpg"
  logo = "/images/xHain_logo3_rev2.png"

  support = "/pages/support"
  about = "/pages/about"
  #legalnotice = "/pages/legal-notice"

  #legalnotice = "/about"
  #cv = "https://www.google.de"



